### PR TITLE
Workflow migrator

### PR DESCRIPTION
**Pull request by jblankendaal**
When deploying a new version of a workflow, existing workflowInstances can now be moved to this new workflow by specifying a new WorkflowMigrator object to the deploy() call of the WorkflowEngine.

### CODE REVIEW

**Comment by tombaeyens** [comment]
you first lock all the workflow instances before doing a deployment.  

i think this should be changed so that you first deploy and then if there is a migrator, then 
1) add a mark to the workflow that migrations have to be done
2) migrate all the workflow instances one by one.
3) remove the mark that migrations have to be done.

this means that it will be easier to run it in a cluster.  it means that all nodes can compete for workflow instances to lock for migrating them.  in case of a crash, the workflow mark allows nodes to detect that migrations still need to occur and start migrating.

@jblankendaal, does it make sense to you as well to revisit the migration in this way?

**Comment by jblankendaal** [comment]
It does make sense to me to first deploy a new workflow and then have a separate migrate call/phase by marking the workflow as "to be migrated".

Do you mean that this migration process should be done async by a separate migration thread? In that case I think I need some more info on how you want that to be implemented. Probably in a similar way as the async work of a workflowInstance?

**Comment by SilentGert** [comment]
Some points about the migration are still unclear to me.

Regarding the locking, if you want to allow the execution of old versions to happen while you are migrating to newer versions, you should probably just mark them. Otherwise you will have to lock them all in order to prevent them from execution. However, if you lock them it would be handy to know that they are locked for migration.

What happens if you deploy two new consecutive version close after each other. Imagine the first migration didn't finish completely, yet. The second migration won't find the oldest workflows because the sourceId is different. 

At the end, I'm curious to see how you do the actual migration of the content. Do you plan on resetting the workflow instance to an earlier stage (some kind of playback) to replay parts that have been changed during the update?

**Comment by jblankendaal** [comment]
@SilentGert 
> Regarding the locking, if you want to allow the execution of old versions to happen while you are migrating to newer versions, you should probably just mark them. Otherwise you will have to lock them all in order to prevent them from execution. However, if you lock them it would be handy to know that they are locked for migration.

Since, because of the remarks of Tom I will (partially) rewrite the migration I'll have to think it over again, but as I see it a whole workflow is either migrated or not. Old workflowInstances can be busy in the old workflow but it is the responsibility of the migrator to wait until they are unlocked (ie finished processing) and then migrate them to the new workflow. I don't think they should be locked until just before each workflowInstance is migrated.

> What happens if you deploy two new consecutive version close after each other. Imagine the first migration didn't finish completely, yet. The second migration won't find the oldest workflows because the sourceId is different.

Good point. On the old workflows there will be a mark: "migrate me to workflow x". The migrator should continue until all workflows having this "migrate me to workflow x" label do not have workflowInstances anymore. It is possible we might need an option to prevent that (an older version of) a workflow is triggered, or that we leave that to the application triggering the workflow.

> At the end, I'm curious to see how you do the actual migration of the content. Do you plan on resetting the workflow instance to an earlier stage (some kind of playback) to replay parts that have been changed during the update? 

The actual migration is quite basic: just change the workflowId on the workflowInstance. That's all we need for now. It is the responsibility of the person/application calling the migrator that in the new workflow no activities are deleted, just added.

**Comment by tombaeyens** [comment]
> a whole workflow is either migrated or not

Waiting until you can lock all workflow instances for a workflow seems overkill to me.  I don't see the problem that some instances keep running in the old version while some are already converted to the new workflow.

Ideally it would be a boolean parameter to specify if you want upfront locking or not.  But I think we should take the gradual upgrade as the first iteration.

**Comment by tombaeyens** [comment]
A note about the locking: please ensure this uses the same field as the other locking.  Because workflow instances locked for migration should not be lockable to process an incoming message.

**Comment by tombaeyens** [comment]
> It is possible we might need an option to prevent that (an older version of) a workflow is triggered, or that we leave that to the application triggering the workflow.

Workflow instances should always start in the latest version.  So there migration doesn't play a role I think.  Not even when you deploy new versions quickly.

**Pull request closed without merging**
